// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateGladiator: typeof import('./components/CreateGladiator.vue')['default']
    Forms: typeof import('./components/Forms.vue')['default']
    Gladiator: typeof import('./components/Gladiator.vue')['default']
    Ludi: typeof import('./components/Ludi.vue')['default']
    Pseudo: typeof import('./components/Pseudo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
